// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: control_v3.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// RESC protocol v3 — the fixed personal-profile contract.
// Normative source: IMPLEMENTATION_PLAN_V11.md §4 + CONTRACT_ERRATA.md.
// This file is the Stage-1 CANDIDATE schema (freeze pending the A0.0 gates
// and independent re-review). It coexists with the legacy v1 control.proto
// until T1 deletes the v1 wire; do not modify without a dated
// CONTRACT_ERRATA.md entry.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Resc_V3_FatalCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case fatalUnspecified // = 0

  /// deterministic
  case profileMismatch // = 1

  /// deterministic
  case buildMismatch // = 2

  /// deterministic
  case versionMismatch // = 3

  /// deterministic
  case malformedFraming // = 4

  /// deterministic
  case recordCapViolation // = 5

  /// deterministic
  case encoderProperty // = 6

  /// deterministic
  case profileInvalid // = 7

  /// deterministic
  case protocolViolation // = 8

  /// deterministic
  case requiredNativeApi // = 9

  /// transient
  case socketFailure // = 10

  /// transient
  case decodeFatal // = 11

  /// transient
  case watchdogAckAge // = 12

  /// transient
  case watchdogOutput // = 13

  /// transient
  case watchdogHandshake // = 14

  /// transient
  case watchdogEncoder // = 15

  /// transient
  case watchdogHeartbeat // = 16

  /// transient
  case identityFailure // = 17

  /// transient (one re-force, then session-fatal)
  case raVerification // = 18

  /// terminal
  case retryBudgetExhausted // = 19

  /// terminal
  case instanceLockHeld // = 20

  /// deterministic
  case permissionDenied // = 21

  /// transient
  case watchdogFirstRa // = 22
  case UNRECOGNIZED(Int)

  public init() {
    self = .fatalUnspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .fatalUnspecified
    case 1: self = .profileMismatch
    case 2: self = .buildMismatch
    case 3: self = .versionMismatch
    case 4: self = .malformedFraming
    case 5: self = .recordCapViolation
    case 6: self = .encoderProperty
    case 7: self = .profileInvalid
    case 8: self = .protocolViolation
    case 9: self = .requiredNativeApi
    case 10: self = .socketFailure
    case 11: self = .decodeFatal
    case 12: self = .watchdogAckAge
    case 13: self = .watchdogOutput
    case 14: self = .watchdogHandshake
    case 15: self = .watchdogEncoder
    case 16: self = .watchdogHeartbeat
    case 17: self = .identityFailure
    case 18: self = .raVerification
    case 19: self = .retryBudgetExhausted
    case 20: self = .instanceLockHeld
    case 21: self = .permissionDenied
    case 22: self = .watchdogFirstRa
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .fatalUnspecified: return 0
    case .profileMismatch: return 1
    case .buildMismatch: return 2
    case .versionMismatch: return 3
    case .malformedFraming: return 4
    case .recordCapViolation: return 5
    case .encoderProperty: return 6
    case .profileInvalid: return 7
    case .protocolViolation: return 8
    case .requiredNativeApi: return 9
    case .socketFailure: return 10
    case .decodeFatal: return 11
    case .watchdogAckAge: return 12
    case .watchdogOutput: return 13
    case .watchdogHandshake: return 14
    case .watchdogEncoder: return 15
    case .watchdogHeartbeat: return 16
    case .identityFailure: return 17
    case .raVerification: return 18
    case .retryBudgetExhausted: return 19
    case .instanceLockHeld: return 20
    case .permissionDenied: return 21
    case .watchdogFirstRa: return 22
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Resc_V3_FatalCode] = [
    .fatalUnspecified,
    .profileMismatch,
    .buildMismatch,
    .versionMismatch,
    .malformedFraming,
    .recordCapViolation,
    .encoderProperty,
    .profileInvalid,
    .protocolViolation,
    .requiredNativeApi,
    .socketFailure,
    .decodeFatal,
    .watchdogAckAge,
    .watchdogOutput,
    .watchdogHandshake,
    .watchdogEncoder,
    .watchdogHeartbeat,
    .identityFailure,
    .raVerification,
    .retryBudgetExhausted,
    .instanceLockHeld,
    .permissionDenied,
    .watchdogFirstRa,
  ]

}

public struct Resc_V3_Envelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sessionRunID: UInt64 = 0

  /// runtime value MUST equal 3
  public var protocolVersion: UInt32 = 0

  public var payload: Resc_V3_Envelope.OneOf_Payload? = nil

  public var displaySettings: Resc_V3_DisplaySettings {
    get {
      if case .displaySettings(let v)? = payload {return v}
      return Resc_V3_DisplaySettings()
    }
    set {payload = .displaySettings(newValue)}
  }

  public var keyEvent: Resc_V3_KeyEvent {
    get {
      if case .keyEvent(let v)? = payload {return v}
      return Resc_V3_KeyEvent()
    }
    set {payload = .keyEvent(newValue)}
  }

  public var hostProfileAnnounce: Resc_V3_HostProfileAnnounce {
    get {
      if case .hostProfileAnnounce(let v)? = payload {return v}
      return Resc_V3_HostProfileAnnounce()
    }
    set {payload = .hostProfileAnnounce(newValue)}
  }

  public var profileResult: Resc_V3_ProfileResult {
    get {
      if case .profileResult(let v)? = payload {return v}
      return Resc_V3_ProfileResult()
    }
    set {payload = .profileResult(newValue)}
  }

  public var frameAck: Resc_V3_FrameAck {
    get {
      if case .frameAck(let v)? = payload {return v}
      return Resc_V3_FrameAck()
    }
    set {payload = .frameAck(newValue)}
  }

  public var buttonEvent: Resc_V3_ButtonEvent {
    get {
      if case .buttonEvent(let v)? = payload {return v}
      return Resc_V3_ButtonEvent()
    }
    set {payload = .buttonEvent(newValue)}
  }

  public var scrollEvent: Resc_V3_ScrollEvent {
    get {
      if case .scrollEvent(let v)? = payload {return v}
      return Resc_V3_ScrollEvent()
    }
    set {payload = .scrollEvent(newValue)}
  }

  public var clockPing: Resc_V3_ClockPing {
    get {
      if case .clockPing(let v)? = payload {return v}
      return Resc_V3_ClockPing()
    }
    set {payload = .clockPing(newValue)}
  }

  public var clockPong: Resc_V3_ClockPong {
    get {
      if case .clockPong(let v)? = payload {return v}
      return Resc_V3_ClockPong()
    }
    set {payload = .clockPong(newValue)}
  }

  public var fatalReport: Resc_V3_FatalReport {
    get {
      if case .fatalReport(let v)? = payload {return v}
      return Resc_V3_FatalReport()
    }
    set {payload = .fatalReport(newValue)}
  }

  public var releaseInput: Resc_V3_ReleaseInput {
    get {
      if case .releaseInput(let v)? = payload {return v}
      return Resc_V3_ReleaseInput()
    }
    set {payload = .releaseInput(newValue)}
  }

  public var heartbeat: Resc_V3_Heartbeat {
    get {
      if case .heartbeat(let v)? = payload {return v}
      return Resc_V3_Heartbeat()
    }
    set {payload = .heartbeat(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    case displaySettings(Resc_V3_DisplaySettings)
    case keyEvent(Resc_V3_KeyEvent)
    case hostProfileAnnounce(Resc_V3_HostProfileAnnounce)
    case profileResult(Resc_V3_ProfileResult)
    case frameAck(Resc_V3_FrameAck)
    case buttonEvent(Resc_V3_ButtonEvent)
    case scrollEvent(Resc_V3_ScrollEvent)
    case clockPing(Resc_V3_ClockPing)
    case clockPong(Resc_V3_ClockPong)
    case fatalReport(Resc_V3_FatalReport)
    case releaseInput(Resc_V3_ReleaseInput)
    case heartbeat(Resc_V3_Heartbeat)

  }

  public init() {}
}

public struct Resc_V3_DisplaySettings: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var warmStrength: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_V3_KeyEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var hidUsage: UInt32 = 0

  public var isDown: Bool = false

  public var modifiers: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_V3_HostProfileAnnounce: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// <= 4096 B
  public var profileCanonical: Data = Data()

  /// exactly 8 B
  public var profileHash: Data = Data()

  /// full lowercase git object id
  public var buildCommit: String = String()

  public var buildDirty: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_V3_ProfileResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var accepted: Bool = false

  /// client's canonical bytes, always present
  public var profileCanonical: Data = Data()

  /// exactly 8 B
  public var profileHash: Data = Data()

  public var buildCommit: String = String()

  public var buildDirty: Bool = false

  /// FATAL_UNSPECIFIED iff accepted
  public var rejectCode: Resc_V3_FatalCode = .fatalUnspecified

  /// true iff accepted
  public var videoListenerReady: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_V3_FrameAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var frameOrdinal: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_V3_ButtonEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// MUST be 0 left, 1 right, 2 middle
  public var button: UInt32 = 0

  public var isDown: Bool = false

  public var xPx: Int32 = 0

  public var yPx: Int32 = 0

  public var modifiers: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_V3_ScrollEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var dx: Int32 = 0

  public var dy: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_V3_ClockPing: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var t1MonoUs: UInt64 = 0

  public var seq: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_V3_ClockPong: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var t1MonoUs: UInt64 = 0

  public var t2MonoUs: UInt64 = 0

  public var t3MonoUs: UInt64 = 0

  public var seq: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_V3_FatalReport: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// MUST be a known nonzero value
  public var code: Resc_V3_FatalCode = .fatalUnspecified

  public var component: String = String()

  public var nativeDomain: String = String()

  public var nativeCode: Int64 = 0

  /// <= 2048 B
  public var summary: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_V3_ReleaseInput: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_V3_Heartbeat: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var tMonoUs: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "resc.v3"

extension Resc_V3_FatalCode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FATAL_UNSPECIFIED\0\u{1}PROFILE_MISMATCH\0\u{1}BUILD_MISMATCH\0\u{1}VERSION_MISMATCH\0\u{1}MALFORMED_FRAMING\0\u{1}RECORD_CAP_VIOLATION\0\u{1}ENCODER_PROPERTY\0\u{1}PROFILE_INVALID\0\u{1}PROTOCOL_VIOLATION\0\u{1}REQUIRED_NATIVE_API\0\u{1}SOCKET_FAILURE\0\u{1}DECODE_FATAL\0\u{1}WATCHDOG_ACK_AGE\0\u{1}WATCHDOG_OUTPUT\0\u{1}WATCHDOG_HANDSHAKE\0\u{1}WATCHDOG_ENCODER\0\u{1}WATCHDOG_HEARTBEAT\0\u{1}IDENTITY_FAILURE\0\u{1}RA_VERIFICATION\0\u{1}RETRY_BUDGET_EXHAUSTED\0\u{1}INSTANCE_LOCK_HELD\0\u{1}PERMISSION_DENIED\0\u{1}WATCHDOG_FIRST_RA\0")
}

extension Resc_V3_Envelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Envelope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_run_id\0\u{3}protocol_version\0\u{4}\u{1e}display_settings\0\u{4}\u{8}key_event\0\u{4}\u{14}host_profile_announce\0\u{3}profile_result\0\u{3}frame_ack\0\u{3}button_event\0\u{3}scroll_event\0\u{3}clock_ping\0\u{3}clock_pong\0\u{4}\u{2}fatal_report\0\u{3}release_input\0\u{1}heartbeat\0\u{c}C\u{1}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.sessionRunID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.protocolVersion) }()
      case 32: try {
        var v: Resc_V3_DisplaySettings?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .displaySettings(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .displaySettings(v)
        }
      }()
      case 40: try {
        var v: Resc_V3_KeyEvent?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .keyEvent(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .keyEvent(v)
        }
      }()
      case 60: try {
        var v: Resc_V3_HostProfileAnnounce?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .hostProfileAnnounce(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .hostProfileAnnounce(v)
        }
      }()
      case 61: try {
        var v: Resc_V3_ProfileResult?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .profileResult(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .profileResult(v)
        }
      }()
      case 62: try {
        var v: Resc_V3_FrameAck?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .frameAck(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .frameAck(v)
        }
      }()
      case 63: try {
        var v: Resc_V3_ButtonEvent?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .buttonEvent(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .buttonEvent(v)
        }
      }()
      case 64: try {
        var v: Resc_V3_ScrollEvent?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .scrollEvent(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .scrollEvent(v)
        }
      }()
      case 65: try {
        var v: Resc_V3_ClockPing?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .clockPing(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .clockPing(v)
        }
      }()
      case 66: try {
        var v: Resc_V3_ClockPong?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .clockPong(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .clockPong(v)
        }
      }()
      case 68: try {
        var v: Resc_V3_FatalReport?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .fatalReport(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .fatalReport(v)
        }
      }()
      case 69: try {
        var v: Resc_V3_ReleaseInput?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .releaseInput(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .releaseInput(v)
        }
      }()
      case 70: try {
        var v: Resc_V3_Heartbeat?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .heartbeat(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .heartbeat(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.sessionRunID != 0 {
      try visitor.visitSingularUInt64Field(value: self.sessionRunID, fieldNumber: 1)
    }
    if self.protocolVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.protocolVersion, fieldNumber: 2)
    }
    switch self.payload {
    case .displaySettings?: try {
      guard case .displaySettings(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 32)
    }()
    case .keyEvent?: try {
      guard case .keyEvent(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 40)
    }()
    case .hostProfileAnnounce?: try {
      guard case .hostProfileAnnounce(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 60)
    }()
    case .profileResult?: try {
      guard case .profileResult(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 61)
    }()
    case .frameAck?: try {
      guard case .frameAck(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 62)
    }()
    case .buttonEvent?: try {
      guard case .buttonEvent(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 63)
    }()
    case .scrollEvent?: try {
      guard case .scrollEvent(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 64)
    }()
    case .clockPing?: try {
      guard case .clockPing(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 65)
    }()
    case .clockPong?: try {
      guard case .clockPong(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 66)
    }()
    case .fatalReport?: try {
      guard case .fatalReport(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 68)
    }()
    case .releaseInput?: try {
      guard case .releaseInput(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 69)
    }()
    case .heartbeat?: try {
      guard case .heartbeat(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 70)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_V3_Envelope, rhs: Resc_V3_Envelope) -> Bool {
    if lhs.sessionRunID != rhs.sessionRunID {return false}
    if lhs.protocolVersion != rhs.protocolVersion {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_V3_DisplaySettings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DisplaySettings"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}warm_strength\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.warmStrength) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.warmStrength.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.warmStrength, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_V3_DisplaySettings, rhs: Resc_V3_DisplaySettings) -> Bool {
    if lhs.warmStrength != rhs.warmStrength {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_V3_KeyEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KeyEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}hid_usage\0\u{3}is_down\0\u{1}modifiers\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.hidUsage) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isDown) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.modifiers) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.hidUsage != 0 {
      try visitor.visitSingularUInt32Field(value: self.hidUsage, fieldNumber: 1)
    }
    if self.isDown != false {
      try visitor.visitSingularBoolField(value: self.isDown, fieldNumber: 2)
    }
    if self.modifiers != 0 {
      try visitor.visitSingularUInt32Field(value: self.modifiers, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_V3_KeyEvent, rhs: Resc_V3_KeyEvent) -> Bool {
    if lhs.hidUsage != rhs.hidUsage {return false}
    if lhs.isDown != rhs.isDown {return false}
    if lhs.modifiers != rhs.modifiers {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_V3_HostProfileAnnounce: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HostProfileAnnounce"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}profile_canonical\0\u{3}profile_hash\0\u{3}build_commit\0\u{3}build_dirty\0\u{c}\u{5}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.profileCanonical) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.profileHash) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.buildCommit) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.buildDirty) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.profileCanonical.isEmpty {
      try visitor.visitSingularBytesField(value: self.profileCanonical, fieldNumber: 1)
    }
    if !self.profileHash.isEmpty {
      try visitor.visitSingularBytesField(value: self.profileHash, fieldNumber: 2)
    }
    if !self.buildCommit.isEmpty {
      try visitor.visitSingularStringField(value: self.buildCommit, fieldNumber: 3)
    }
    if self.buildDirty != false {
      try visitor.visitSingularBoolField(value: self.buildDirty, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_V3_HostProfileAnnounce, rhs: Resc_V3_HostProfileAnnounce) -> Bool {
    if lhs.profileCanonical != rhs.profileCanonical {return false}
    if lhs.profileHash != rhs.profileHash {return false}
    if lhs.buildCommit != rhs.buildCommit {return false}
    if lhs.buildDirty != rhs.buildDirty {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_V3_ProfileResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProfileResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}accepted\0\u{3}profile_canonical\0\u{3}profile_hash\0\u{3}build_commit\0\u{3}build_dirty\0\u{3}reject_code\0\u{3}video_listener_ready\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.profileCanonical) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.profileHash) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.buildCommit) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.buildDirty) }()
      case 6: try { try decoder.decodeSingularEnumField(value: &self.rejectCode) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.videoListenerReady) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 1)
    }
    if !self.profileCanonical.isEmpty {
      try visitor.visitSingularBytesField(value: self.profileCanonical, fieldNumber: 2)
    }
    if !self.profileHash.isEmpty {
      try visitor.visitSingularBytesField(value: self.profileHash, fieldNumber: 3)
    }
    if !self.buildCommit.isEmpty {
      try visitor.visitSingularStringField(value: self.buildCommit, fieldNumber: 4)
    }
    if self.buildDirty != false {
      try visitor.visitSingularBoolField(value: self.buildDirty, fieldNumber: 5)
    }
    if self.rejectCode != .fatalUnspecified {
      try visitor.visitSingularEnumField(value: self.rejectCode, fieldNumber: 6)
    }
    if self.videoListenerReady != false {
      try visitor.visitSingularBoolField(value: self.videoListenerReady, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_V3_ProfileResult, rhs: Resc_V3_ProfileResult) -> Bool {
    if lhs.accepted != rhs.accepted {return false}
    if lhs.profileCanonical != rhs.profileCanonical {return false}
    if lhs.profileHash != rhs.profileHash {return false}
    if lhs.buildCommit != rhs.buildCommit {return false}
    if lhs.buildDirty != rhs.buildDirty {return false}
    if lhs.rejectCode != rhs.rejectCode {return false}
    if lhs.videoListenerReady != rhs.videoListenerReady {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_V3_FrameAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FrameAck"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}frame_ordinal\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.frameOrdinal) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.frameOrdinal != 0 {
      try visitor.visitSingularUInt64Field(value: self.frameOrdinal, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_V3_FrameAck, rhs: Resc_V3_FrameAck) -> Bool {
    if lhs.frameOrdinal != rhs.frameOrdinal {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_V3_ButtonEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ButtonEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}button\0\u{3}is_down\0\u{3}x_px\0\u{3}y_px\0\u{1}modifiers\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.button) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isDown) }()
      case 3: try { try decoder.decodeSingularSInt32Field(value: &self.xPx) }()
      case 4: try { try decoder.decodeSingularSInt32Field(value: &self.yPx) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.modifiers) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.button != 0 {
      try visitor.visitSingularUInt32Field(value: self.button, fieldNumber: 1)
    }
    if self.isDown != false {
      try visitor.visitSingularBoolField(value: self.isDown, fieldNumber: 2)
    }
    if self.xPx != 0 {
      try visitor.visitSingularSInt32Field(value: self.xPx, fieldNumber: 3)
    }
    if self.yPx != 0 {
      try visitor.visitSingularSInt32Field(value: self.yPx, fieldNumber: 4)
    }
    if self.modifiers != 0 {
      try visitor.visitSingularUInt32Field(value: self.modifiers, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_V3_ButtonEvent, rhs: Resc_V3_ButtonEvent) -> Bool {
    if lhs.button != rhs.button {return false}
    if lhs.isDown != rhs.isDown {return false}
    if lhs.xPx != rhs.xPx {return false}
    if lhs.yPx != rhs.yPx {return false}
    if lhs.modifiers != rhs.modifiers {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_V3_ScrollEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ScrollEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}dx\0\u{1}dy\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularSInt32Field(value: &self.dx) }()
      case 2: try { try decoder.decodeSingularSInt32Field(value: &self.dy) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.dx != 0 {
      try visitor.visitSingularSInt32Field(value: self.dx, fieldNumber: 1)
    }
    if self.dy != 0 {
      try visitor.visitSingularSInt32Field(value: self.dy, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_V3_ScrollEvent, rhs: Resc_V3_ScrollEvent) -> Bool {
    if lhs.dx != rhs.dx {return false}
    if lhs.dy != rhs.dy {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_V3_ClockPing: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClockPing"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}t1_mono_us\0\u{1}seq\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.t1MonoUs) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.seq) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.t1MonoUs != 0 {
      try visitor.visitSingularUInt64Field(value: self.t1MonoUs, fieldNumber: 1)
    }
    if self.seq != 0 {
      try visitor.visitSingularUInt32Field(value: self.seq, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_V3_ClockPing, rhs: Resc_V3_ClockPing) -> Bool {
    if lhs.t1MonoUs != rhs.t1MonoUs {return false}
    if lhs.seq != rhs.seq {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_V3_ClockPong: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClockPong"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}t1_mono_us\0\u{3}t2_mono_us\0\u{3}t3_mono_us\0\u{1}seq\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.t1MonoUs) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.t2MonoUs) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.t3MonoUs) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.seq) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.t1MonoUs != 0 {
      try visitor.visitSingularUInt64Field(value: self.t1MonoUs, fieldNumber: 1)
    }
    if self.t2MonoUs != 0 {
      try visitor.visitSingularUInt64Field(value: self.t2MonoUs, fieldNumber: 2)
    }
    if self.t3MonoUs != 0 {
      try visitor.visitSingularUInt64Field(value: self.t3MonoUs, fieldNumber: 3)
    }
    if self.seq != 0 {
      try visitor.visitSingularUInt32Field(value: self.seq, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_V3_ClockPong, rhs: Resc_V3_ClockPong) -> Bool {
    if lhs.t1MonoUs != rhs.t1MonoUs {return false}
    if lhs.t2MonoUs != rhs.t2MonoUs {return false}
    if lhs.t3MonoUs != rhs.t3MonoUs {return false}
    if lhs.seq != rhs.seq {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_V3_FatalReport: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FatalReport"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}component\0\u{3}native_domain\0\u{3}native_code\0\u{1}summary\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.component) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.nativeDomain) }()
      case 4: try { try decoder.decodeSingularSInt64Field(value: &self.nativeCode) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.summary) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != .fatalUnspecified {
      try visitor.visitSingularEnumField(value: self.code, fieldNumber: 1)
    }
    if !self.component.isEmpty {
      try visitor.visitSingularStringField(value: self.component, fieldNumber: 2)
    }
    if !self.nativeDomain.isEmpty {
      try visitor.visitSingularStringField(value: self.nativeDomain, fieldNumber: 3)
    }
    if self.nativeCode != 0 {
      try visitor.visitSingularSInt64Field(value: self.nativeCode, fieldNumber: 4)
    }
    if !self.summary.isEmpty {
      try visitor.visitSingularStringField(value: self.summary, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_V3_FatalReport, rhs: Resc_V3_FatalReport) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.component != rhs.component {return false}
    if lhs.nativeDomain != rhs.nativeDomain {return false}
    if lhs.nativeCode != rhs.nativeCode {return false}
    if lhs.summary != rhs.summary {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_V3_ReleaseInput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReleaseInput"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_V3_ReleaseInput, rhs: Resc_V3_ReleaseInput) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_V3_Heartbeat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Heartbeat"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}t_mono_us\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.tMonoUs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.tMonoUs != 0 {
      try visitor.visitSingularUInt64Field(value: self.tMonoUs, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_V3_Heartbeat, rhs: Resc_V3_Heartbeat) -> Bool {
    if lhs.tMonoUs != rhs.tMonoUs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
