// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: control.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Resc_Control_Rotation: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case rotation0 // = 0
  case rotation90 // = 1
  case rotation180 // = 2
  case rotation270 // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .rotation0
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .rotation0
    case 1: self = .rotation90
    case 2: self = .rotation180
    case 3: self = .rotation270
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .rotation0: return 0
    case .rotation90: return 1
    case .rotation180: return 2
    case .rotation270: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Resc_Control_Rotation] = [
    .rotation0,
    .rotation90,
    .rotation180,
    .rotation270,
  ]

}

public enum Resc_Control_Codec: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case h264 // = 0
  case hevc // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .h264
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .h264
    case 1: self = .hevc
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .h264: return 0
    case .hevc: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Resc_Control_Codec] = [
    .h264,
    .hevc,
  ]

}

public enum Resc_Control_CodecProfile: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case profileUnspecified // = 0

  /// H.264 profiles
  case h264Baseline // = 1
  case h264Main // = 2
  case h264High // = 3

  /// HEVC profiles (Phase 8+)
  case hevcMain // = 10
  case hevcMain10 // = 11
  case UNRECOGNIZED(Int)

  public init() {
    self = .profileUnspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .profileUnspecified
    case 1: self = .h264Baseline
    case 2: self = .h264Main
    case 3: self = .h264High
    case 10: self = .hevcMain
    case 11: self = .hevcMain10
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .profileUnspecified: return 0
    case .h264Baseline: return 1
    case .h264Main: return 2
    case .h264High: return 3
    case .hevcMain: return 10
    case .hevcMain10: return 11
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Resc_Control_CodecProfile] = [
    .profileUnspecified,
    .h264Baseline,
    .h264Main,
    .h264High,
    .hevcMain,
    .hevcMain10,
  ]

}

public struct Resc_Control_Envelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 0 until assigned by host in ModeConfirm
  public var sessionID: UInt64 = 0

  /// must equal PROTOCOL_VERSION (=1)
  public var protocolVersion: UInt32 = 0

  public var payload: Resc_Control_Envelope.OneOf_Payload? = nil

  /// Pairing (10–19)
  public var pairRequest: Resc_Control_PairRequest {
    get {
      if case .pairRequest(let v)? = payload {return v}
      return Resc_Control_PairRequest()
    }
    set {payload = .pairRequest(newValue)}
  }

  public var pairResponse: Resc_Control_PairResponse {
    get {
      if case .pairResponse(let v)? = payload {return v}
      return Resc_Control_PairResponse()
    }
    set {payload = .pairResponse(newValue)}
  }

  /// Mode negotiation (20–29)
  public var modeRequest: Resc_Control_ModeRequest {
    get {
      if case .modeRequest(let v)? = payload {return v}
      return Resc_Control_ModeRequest()
    }
    set {payload = .modeRequest(newValue)}
  }

  public var modeConfirm: Resc_Control_ModeConfirm {
    get {
      if case .modeConfirm(let v)? = payload {return v}
      return Resc_Control_ModeConfirm()
    }
    set {payload = .modeConfirm(newValue)}
  }

  public var modeReject: Resc_Control_ModeReject {
    get {
      if case .modeReject(let v)? = payload {return v}
      return Resc_Control_ModeReject()
    }
    set {payload = .modeReject(newValue)}
  }

  public var startStreaming: Resc_Control_StartStreaming {
    get {
      if case .startStreaming(let v)? = payload {return v}
      return Resc_Control_StartStreaming()
    }
    set {payload = .startStreaming(newValue)}
  }

  public var streamingReady: Resc_Control_StreamingReady {
    get {
      if case .streamingReady(let v)? = payload {return v}
      return Resc_Control_StreamingReady()
    }
    set {payload = .streamingReady(newValue)}
  }

  /// Runtime (30–39)
  public var stats: Resc_Control_Stats {
    get {
      if case .stats(let v)? = payload {return v}
      return Resc_Control_Stats()
    }
    set {payload = .stats(newValue)}
  }

  public var requestIdr: Resc_Control_RequestIDR {
    get {
      if case .requestIdr(let v)? = payload {return v}
      return Resc_Control_RequestIDR()
    }
    set {payload = .requestIdr(newValue)}
  }

  public var displaySettings: Resc_Control_DisplaySettings {
    get {
      if case .displaySettings(let v)? = payload {return v}
      return Resc_Control_DisplaySettings()
    }
    set {payload = .displaySettings(newValue)}
  }

  /// Input (40–49)
  public var keyEvent: Resc_Control_KeyEvent {
    get {
      if case .keyEvent(let v)? = payload {return v}
      return Resc_Control_KeyEvent()
    }
    set {payload = .keyEvent(newValue)}
  }

  /// Lifecycle (50–59)
  public var stopStreaming: Resc_Control_StopStreaming {
    get {
      if case .stopStreaming(let v)? = payload {return v}
      return Resc_Control_StopStreaming()
    }
    set {payload = .stopStreaming(newValue)}
  }

  /// A0.0 additive trace-mode clock sync (60–69 reserved for v3 numbers;
  /// 65/66 intentionally match resc.v3 so the semantics carry over at T1).
  /// Wire-compatible addition; legacy peers ignore unknown fields.
  public var clockPing: Resc_Control_ClockPing {
    get {
      if case .clockPing(let v)? = payload {return v}
      return Resc_Control_ClockPing()
    }
    set {payload = .clockPing(newValue)}
  }

  public var clockPong: Resc_Control_ClockPong {
    get {
      if case .clockPong(let v)? = payload {return v}
      return Resc_Control_ClockPong()
    }
    set {payload = .clockPong(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    /// Pairing (10–19)
    case pairRequest(Resc_Control_PairRequest)
    case pairResponse(Resc_Control_PairResponse)
    /// Mode negotiation (20–29)
    case modeRequest(Resc_Control_ModeRequest)
    case modeConfirm(Resc_Control_ModeConfirm)
    case modeReject(Resc_Control_ModeReject)
    case startStreaming(Resc_Control_StartStreaming)
    case streamingReady(Resc_Control_StreamingReady)
    /// Runtime (30–39)
    case stats(Resc_Control_Stats)
    case requestIdr(Resc_Control_RequestIDR)
    case displaySettings(Resc_Control_DisplaySettings)
    /// Input (40–49)
    case keyEvent(Resc_Control_KeyEvent)
    /// Lifecycle (50–59)
    case stopStreaming(Resc_Control_StopStreaming)
    /// A0.0 additive trace-mode clock sync (60–69 reserved for v3 numbers;
    /// 65/66 intentionally match resc.v3 so the semantics carry over at T1).
    /// Wire-compatible addition; legacy peers ignore unknown fields.
    case clockPing(Resc_Control_ClockPing)
    case clockPong(Resc_Control_ClockPong)

  }

  public init() {}
}

/// Four-timestamp trace-mode clock sync (A0.0). t1 is the requester's
/// monotonic µs; t2/t3 are the responder's receive/send monotonic µs.
/// The requester records t4 locally. Diagnostics only — never flow control.
public struct Resc_Control_ClockPing: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var t1MonoUs: UInt64 = 0

  public var seq: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_Control_ClockPong: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var t1MonoUs: UInt64 = 0

  public var t2MonoUs: UInt64 = 0

  public var t3MonoUs: UInt64 = 0

  public var seq: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_Control_PairRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 6-digit PIN displayed by host UI
  public var pin: String = String()

  /// stable client ID stored on disk (UUID)
  public var clientDeviceID: String = String()

  /// 16 random bytes for replay protection
  public var nonce: Data = Data()

  /// reject if >60s skew
  public var timestampUnixMs: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_Control_PairResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// SHA-256, 32 bytes
  public var hostCertFingerprint: Data = Data()

  /// stable host ID stored on disk (UUID)
  public var hostDeviceID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_Control_ModeRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// must equal PROTOCOL_VERSION; mismatch → ModeReject
  public var protocolVersion: UInt32 = 0

  /// ordered by preference
  public var preferredModes: [Resc_Control_DisplayMode] = []

  public var rotation: Resc_Control_Rotation = .rotation0

  /// present from day one; ignored in phases 1–7
  public var supportedCodecs: [Resc_Control_Codec] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_Control_DisplayMode: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var width: UInt32 = 0

  public var height: UInt32 = 0

  /// e.g. 60000 for 60 Hz
  public var refreshRateMillihz: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_Control_ModeConfirm: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// host-assigned; also set in Envelope.session_id
  public var sessionID: UInt64 {
    get {_storage._sessionID}
    set {_uniqueStorage()._sessionID = newValue}
  }

  /// IDs for filtering UDP packets.
  public var streamID: UInt32 {
    get {_storage._streamID}
    set {_uniqueStorage()._streamID = newValue}
  }

  public var configID: UInt32 {
    get {_storage._configID}
    set {_uniqueStorage()._configID = newValue}
  }

  /// Actual mode applied by host.
  public var actualWidth: UInt32 {
    get {_storage._actualWidth}
    set {_uniqueStorage()._actualWidth = newValue}
  }

  public var actualHeight: UInt32 {
    get {_storage._actualHeight}
    set {_uniqueStorage()._actualHeight = newValue}
  }

  public var actualRefreshRateMillihz: UInt32 {
    get {_storage._actualRefreshRateMillihz}
    set {_uniqueStorage()._actualRefreshRateMillihz = newValue}
  }

  public var actualRotation: Resc_Control_Rotation {
    get {_storage._actualRotation}
    set {_uniqueStorage()._actualRotation = newValue}
  }

  /// StreamSpace dimensions (= virtual display pixel resolution).
  public var streamWidth: UInt32 {
    get {_storage._streamWidth}
    set {_uniqueStorage()._streamWidth = newValue}
  }

  public var streamHeight: UInt32 {
    get {_storage._streamHeight}
    set {_uniqueStorage()._streamHeight = newValue}
  }

  /// Codec info.
  public var codec: Resc_Control_Codec {
    get {_storage._codec}
    set {_uniqueStorage()._codec = newValue}
  }

  /// H264_HIGH in MVP
  public var codecProfile: Resc_Control_CodecProfile {
    get {_storage._codecProfile}
    set {_uniqueStorage()._codecProfile = newValue}
  }

  /// 41 or 51 (H.264 level_idc convention)
  public var codecLevelIdc: UInt32 {
    get {_storage._codecLevelIdc}
    set {_uniqueStorage()._codecLevelIdc = newValue}
  }

  /// Initial encoder bitrate (host-selected).
  public var bitrateBps: UInt32 {
    get {_storage._bitrateBps}
    set {_uniqueStorage()._bitrateBps = newValue}
  }

  /// Transport sizing / receiver preallocation.
  public var maxDatagramBytes: UInt32 {
    get {_storage._maxDatagramBytes}
    set {_uniqueStorage()._maxDatagramBytes = newValue}
  }

  /// 1362
  public var maxVideoPayloadBytes: UInt32 {
    get {_storage._maxVideoPayloadBytes}
    set {_uniqueStorage()._maxVideoPayloadBytes = newValue}
  }

  /// e.g. 256
  public var maxTotalChunksPerFrame: UInt32 {
    get {_storage._maxTotalChunksPerFrame}
    set {_uniqueStorage()._maxTotalChunksPerFrame = newValue}
  }

  /// MUST be non-zero for 4K60
  public var maxFrameBytes: UInt32 {
    get {_storage._maxFrameBytes}
    set {_uniqueStorage()._maxFrameBytes = newValue}
  }

  /// Ports for UDP side channels.
  public var videoPort: UInt32 {
    get {_storage._videoPort}
    set {_uniqueStorage()._videoPort = newValue}
  }

  public var inputUdpPort: UInt32 {
    get {_storage._inputUdpPort}
    set {_uniqueStorage()._inputUdpPort = newValue}
  }

  public var cursorUdpPort: UInt32 {
    get {_storage._cursorUdpPort}
    set {_uniqueStorage()._cursorUdpPort = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Resc_Control_ModeReject: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reason: Resc_Control_ModeReject.Reason = .unspecified

  /// human-readable debug string
  public var message: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Reason: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unspecified // = 0
    case incompatibleProtocolVersion // = 1
    case notPaired // = 2
    case unsupportedMode // = 3
    case internalError // = 4
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .incompatibleProtocolVersion
      case 2: self = .notPaired
      case 3: self = .unsupportedMode
      case 4: self = .internalError
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .incompatibleProtocolVersion: return 1
      case .notPaired: return 2
      case .unsupportedMode: return 3
      case .internalError: return 4
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Resc_Control_ModeReject.Reason] = [
      .unspecified,
      .incompatibleProtocolVersion,
      .notPaired,
      .unsupportedMode,
      .internalError,
    ]

  }

  public init() {}
}

public struct Resc_Control_StartStreaming: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: UInt32 = 0

  public var configID: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_Control_StreamingReady: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: UInt32 = 0

  public var configID: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_Control_Stats: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 0.0–1.0
  public var packetLossRate: Float = 0

  /// 0.0–1.0
  public var frameDropRate: Float = 0

  /// 95th percentile decode time
  public var decodeMsP95: UInt32 = 0

  /// Debug counters.
  public var misroutedPackets: UInt32 = 0

  public var unsupportedVersionPackets: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_Control_RequestIDR: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: UInt32 = 0

  public var configID: UInt32 = 0

  public var reason: Resc_Control_RequestIDR.Reason = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Reason: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unspecified // = 0
    case frameLoss // = 1
    case decodeError // = 2
    case parameterSetLoss // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .frameLoss
      case 2: self = .decodeError
      case 3: self = .parameterSetLoss
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .frameLoss: return 1
      case .decodeError: return 2
      case .parameterSetLoss: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Resc_Control_RequestIDR.Reason] = [
      .unspecified,
      .frameLoss,
      .decodeError,
      .parameterSetLoss,
    ]

  }

  public init() {}
}

/// Host → Client display settings (e.g., Night Shift warm filter)
public struct Resc_Control_DisplaySettings: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 0.0 = off, 1.0 = maximum warmth
  public var warmStrength: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_Control_KeyEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var seq: UInt32 = 0

  /// protobuf bool is well-defined; UDP structs use u8
  public var isDown: Bool = false

  /// Client sends both fields:
  public var hidUsage: UInt32 = 0

  /// SDL keysym / Unicode codepoint (layout-dependent)
  public var logicalKeysym: UInt32 = 0

  /// modifiers snapshot for debug/telemetry
  public var modifiers: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Resc_Control_StopStreaming: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reason: Resc_Control_StopStreaming.Reason = .unspecified

  public var message: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Reason: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unspecified // = 0
    case userRequest // = 1
    case gracePeriodExpired // = 2
    case internalError // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .userRequest
      case 2: self = .gracePeriodExpired
      case 3: self = .internalError
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .userRequest: return 1
      case .gracePeriodExpired: return 2
      case .internalError: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Resc_Control_StopStreaming.Reason] = [
      .unspecified,
      .userRequest,
      .gracePeriodExpired,
      .internalError,
    ]

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "resc.control"

extension Resc_Control_Rotation: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ROTATION_0\0\u{1}ROTATION_90\0\u{1}ROTATION_180\0\u{1}ROTATION_270\0")
}

extension Resc_Control_Codec: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CODEC_H264\0\u{1}CODEC_HEVC\0")
}

extension Resc_Control_CodecProfile: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PROFILE_UNSPECIFIED\0\u{1}H264_BASELINE\0\u{1}H264_MAIN\0\u{1}H264_HIGH\0\u{2}\u{7}HEVC_MAIN\0\u{1}HEVC_MAIN10\0")
}

extension Resc_Control_Envelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Envelope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_id\0\u{3}protocol_version\0\u{4}\u{8}pair_request\0\u{3}pair_response\0\u{4}\u{9}mode_request\0\u{3}mode_confirm\0\u{3}mode_reject\0\u{3}start_streaming\0\u{3}streaming_ready\0\u{2}\u{6}stats\0\u{3}request_idr\0\u{3}display_settings\0\u{4}\u{8}key_event\0\u{4}\u{a}stop_streaming\0\u{4}\u{f}clock_ping\0\u{3}clock_pong\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.sessionID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.protocolVersion) }()
      case 10: try {
        var v: Resc_Control_PairRequest?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .pairRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .pairRequest(v)
        }
      }()
      case 11: try {
        var v: Resc_Control_PairResponse?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .pairResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .pairResponse(v)
        }
      }()
      case 20: try {
        var v: Resc_Control_ModeRequest?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .modeRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .modeRequest(v)
        }
      }()
      case 21: try {
        var v: Resc_Control_ModeConfirm?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .modeConfirm(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .modeConfirm(v)
        }
      }()
      case 22: try {
        var v: Resc_Control_ModeReject?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .modeReject(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .modeReject(v)
        }
      }()
      case 23: try {
        var v: Resc_Control_StartStreaming?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .startStreaming(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .startStreaming(v)
        }
      }()
      case 24: try {
        var v: Resc_Control_StreamingReady?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .streamingReady(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .streamingReady(v)
        }
      }()
      case 30: try {
        var v: Resc_Control_Stats?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .stats(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .stats(v)
        }
      }()
      case 31: try {
        var v: Resc_Control_RequestIDR?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .requestIdr(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .requestIdr(v)
        }
      }()
      case 32: try {
        var v: Resc_Control_DisplaySettings?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .displaySettings(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .displaySettings(v)
        }
      }()
      case 40: try {
        var v: Resc_Control_KeyEvent?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .keyEvent(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .keyEvent(v)
        }
      }()
      case 50: try {
        var v: Resc_Control_StopStreaming?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .stopStreaming(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .stopStreaming(v)
        }
      }()
      case 65: try {
        var v: Resc_Control_ClockPing?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .clockPing(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .clockPing(v)
        }
      }()
      case 66: try {
        var v: Resc_Control_ClockPong?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .clockPong(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .clockPong(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.sessionID != 0 {
      try visitor.visitSingularUInt64Field(value: self.sessionID, fieldNumber: 1)
    }
    if self.protocolVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.protocolVersion, fieldNumber: 2)
    }
    switch self.payload {
    case .pairRequest?: try {
      guard case .pairRequest(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .pairResponse?: try {
      guard case .pairResponse(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .modeRequest?: try {
      guard case .modeRequest(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
    }()
    case .modeConfirm?: try {
      guard case .modeConfirm(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
    }()
    case .modeReject?: try {
      guard case .modeReject(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 22)
    }()
    case .startStreaming?: try {
      guard case .startStreaming(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 23)
    }()
    case .streamingReady?: try {
      guard case .streamingReady(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 24)
    }()
    case .stats?: try {
      guard case .stats(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 30)
    }()
    case .requestIdr?: try {
      guard case .requestIdr(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 31)
    }()
    case .displaySettings?: try {
      guard case .displaySettings(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 32)
    }()
    case .keyEvent?: try {
      guard case .keyEvent(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 40)
    }()
    case .stopStreaming?: try {
      guard case .stopStreaming(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 50)
    }()
    case .clockPing?: try {
      guard case .clockPing(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 65)
    }()
    case .clockPong?: try {
      guard case .clockPong(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 66)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_Envelope, rhs: Resc_Control_Envelope) -> Bool {
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.protocolVersion != rhs.protocolVersion {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_ClockPing: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClockPing"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}t1_mono_us\0\u{1}seq\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.t1MonoUs) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.seq) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.t1MonoUs != 0 {
      try visitor.visitSingularUInt64Field(value: self.t1MonoUs, fieldNumber: 1)
    }
    if self.seq != 0 {
      try visitor.visitSingularUInt32Field(value: self.seq, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_ClockPing, rhs: Resc_Control_ClockPing) -> Bool {
    if lhs.t1MonoUs != rhs.t1MonoUs {return false}
    if lhs.seq != rhs.seq {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_ClockPong: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClockPong"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}t1_mono_us\0\u{3}t2_mono_us\0\u{3}t3_mono_us\0\u{1}seq\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.t1MonoUs) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.t2MonoUs) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.t3MonoUs) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.seq) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.t1MonoUs != 0 {
      try visitor.visitSingularUInt64Field(value: self.t1MonoUs, fieldNumber: 1)
    }
    if self.t2MonoUs != 0 {
      try visitor.visitSingularUInt64Field(value: self.t2MonoUs, fieldNumber: 2)
    }
    if self.t3MonoUs != 0 {
      try visitor.visitSingularUInt64Field(value: self.t3MonoUs, fieldNumber: 3)
    }
    if self.seq != 0 {
      try visitor.visitSingularUInt32Field(value: self.seq, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_ClockPong, rhs: Resc_Control_ClockPong) -> Bool {
    if lhs.t1MonoUs != rhs.t1MonoUs {return false}
    if lhs.t2MonoUs != rhs.t2MonoUs {return false}
    if lhs.t3MonoUs != rhs.t3MonoUs {return false}
    if lhs.seq != rhs.seq {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_PairRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PairRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}pin\0\u{3}client_device_id\0\u{1}nonce\0\u{3}timestamp_unix_ms\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.pin) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.clientDeviceID) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.nonce) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.timestampUnixMs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.pin.isEmpty {
      try visitor.visitSingularStringField(value: self.pin, fieldNumber: 1)
    }
    if !self.clientDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.clientDeviceID, fieldNumber: 2)
    }
    if !self.nonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.nonce, fieldNumber: 3)
    }
    if self.timestampUnixMs != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestampUnixMs, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_PairRequest, rhs: Resc_Control_PairRequest) -> Bool {
    if lhs.pin != rhs.pin {return false}
    if lhs.clientDeviceID != rhs.clientDeviceID {return false}
    if lhs.nonce != rhs.nonce {return false}
    if lhs.timestampUnixMs != rhs.timestampUnixMs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_PairResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PairResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}host_cert_fingerprint\0\u{3}host_device_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.hostCertFingerprint) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.hostDeviceID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.hostCertFingerprint.isEmpty {
      try visitor.visitSingularBytesField(value: self.hostCertFingerprint, fieldNumber: 1)
    }
    if !self.hostDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.hostDeviceID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_PairResponse, rhs: Resc_Control_PairResponse) -> Bool {
    if lhs.hostCertFingerprint != rhs.hostCertFingerprint {return false}
    if lhs.hostDeviceID != rhs.hostDeviceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_ModeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ModeRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}protocol_version\0\u{3}preferred_modes\0\u{1}rotation\0\u{3}supported_codecs\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.protocolVersion) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.preferredModes) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.rotation) }()
      case 4: try { try decoder.decodeRepeatedEnumField(value: &self.supportedCodecs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.protocolVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.protocolVersion, fieldNumber: 1)
    }
    if !self.preferredModes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.preferredModes, fieldNumber: 2)
    }
    if self.rotation != .rotation0 {
      try visitor.visitSingularEnumField(value: self.rotation, fieldNumber: 3)
    }
    if !self.supportedCodecs.isEmpty {
      try visitor.visitPackedEnumField(value: self.supportedCodecs, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_ModeRequest, rhs: Resc_Control_ModeRequest) -> Bool {
    if lhs.protocolVersion != rhs.protocolVersion {return false}
    if lhs.preferredModes != rhs.preferredModes {return false}
    if lhs.rotation != rhs.rotation {return false}
    if lhs.supportedCodecs != rhs.supportedCodecs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_DisplayMode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DisplayMode"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}width\0\u{1}height\0\u{3}refresh_rate_millihz\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.width) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.height) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.refreshRateMillihz) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.width != 0 {
      try visitor.visitSingularUInt32Field(value: self.width, fieldNumber: 1)
    }
    if self.height != 0 {
      try visitor.visitSingularUInt32Field(value: self.height, fieldNumber: 2)
    }
    if self.refreshRateMillihz != 0 {
      try visitor.visitSingularUInt32Field(value: self.refreshRateMillihz, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_DisplayMode, rhs: Resc_Control_DisplayMode) -> Bool {
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.refreshRateMillihz != rhs.refreshRateMillihz {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_ModeConfirm: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ModeConfirm"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_id\0\u{3}stream_id\0\u{3}config_id\0\u{3}actual_width\0\u{3}actual_height\0\u{3}actual_refresh_rate_millihz\0\u{3}actual_rotation\0\u{3}stream_width\0\u{3}stream_height\0\u{1}codec\0\u{3}codec_profile\0\u{3}codec_level_idc\0\u{3}bitrate_bps\0\u{3}max_datagram_bytes\0\u{3}max_video_payload_bytes\0\u{3}max_total_chunks_per_frame\0\u{3}max_frame_bytes\0\u{4}\u{3}video_port\0\u{3}input_udp_port\0\u{3}cursor_udp_port\0")

  fileprivate class _StorageClass {
    var _sessionID: UInt64 = 0
    var _streamID: UInt32 = 0
    var _configID: UInt32 = 0
    var _actualWidth: UInt32 = 0
    var _actualHeight: UInt32 = 0
    var _actualRefreshRateMillihz: UInt32 = 0
    var _actualRotation: Resc_Control_Rotation = .rotation0
    var _streamWidth: UInt32 = 0
    var _streamHeight: UInt32 = 0
    var _codec: Resc_Control_Codec = .h264
    var _codecProfile: Resc_Control_CodecProfile = .profileUnspecified
    var _codecLevelIdc: UInt32 = 0
    var _bitrateBps: UInt32 = 0
    var _maxDatagramBytes: UInt32 = 0
    var _maxVideoPayloadBytes: UInt32 = 0
    var _maxTotalChunksPerFrame: UInt32 = 0
    var _maxFrameBytes: UInt32 = 0
    var _videoPort: UInt32 = 0
    var _inputUdpPort: UInt32 = 0
    var _cursorUdpPort: UInt32 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _sessionID = source._sessionID
      _streamID = source._streamID
      _configID = source._configID
      _actualWidth = source._actualWidth
      _actualHeight = source._actualHeight
      _actualRefreshRateMillihz = source._actualRefreshRateMillihz
      _actualRotation = source._actualRotation
      _streamWidth = source._streamWidth
      _streamHeight = source._streamHeight
      _codec = source._codec
      _codecProfile = source._codecProfile
      _codecLevelIdc = source._codecLevelIdc
      _bitrateBps = source._bitrateBps
      _maxDatagramBytes = source._maxDatagramBytes
      _maxVideoPayloadBytes = source._maxVideoPayloadBytes
      _maxTotalChunksPerFrame = source._maxTotalChunksPerFrame
      _maxFrameBytes = source._maxFrameBytes
      _videoPort = source._videoPort
      _inputUdpPort = source._inputUdpPort
      _cursorUdpPort = source._cursorUdpPort
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt64Field(value: &_storage._sessionID) }()
        case 2: try { try decoder.decodeSingularUInt32Field(value: &_storage._streamID) }()
        case 3: try { try decoder.decodeSingularUInt32Field(value: &_storage._configID) }()
        case 4: try { try decoder.decodeSingularUInt32Field(value: &_storage._actualWidth) }()
        case 5: try { try decoder.decodeSingularUInt32Field(value: &_storage._actualHeight) }()
        case 6: try { try decoder.decodeSingularUInt32Field(value: &_storage._actualRefreshRateMillihz) }()
        case 7: try { try decoder.decodeSingularEnumField(value: &_storage._actualRotation) }()
        case 8: try { try decoder.decodeSingularUInt32Field(value: &_storage._streamWidth) }()
        case 9: try { try decoder.decodeSingularUInt32Field(value: &_storage._streamHeight) }()
        case 10: try { try decoder.decodeSingularEnumField(value: &_storage._codec) }()
        case 11: try { try decoder.decodeSingularEnumField(value: &_storage._codecProfile) }()
        case 12: try { try decoder.decodeSingularUInt32Field(value: &_storage._codecLevelIdc) }()
        case 13: try { try decoder.decodeSingularUInt32Field(value: &_storage._bitrateBps) }()
        case 14: try { try decoder.decodeSingularUInt32Field(value: &_storage._maxDatagramBytes) }()
        case 15: try { try decoder.decodeSingularUInt32Field(value: &_storage._maxVideoPayloadBytes) }()
        case 16: try { try decoder.decodeSingularUInt32Field(value: &_storage._maxTotalChunksPerFrame) }()
        case 17: try { try decoder.decodeSingularUInt32Field(value: &_storage._maxFrameBytes) }()
        case 20: try { try decoder.decodeSingularUInt32Field(value: &_storage._videoPort) }()
        case 21: try { try decoder.decodeSingularUInt32Field(value: &_storage._inputUdpPort) }()
        case 22: try { try decoder.decodeSingularUInt32Field(value: &_storage._cursorUdpPort) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._sessionID != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._sessionID, fieldNumber: 1)
      }
      if _storage._streamID != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._streamID, fieldNumber: 2)
      }
      if _storage._configID != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._configID, fieldNumber: 3)
      }
      if _storage._actualWidth != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._actualWidth, fieldNumber: 4)
      }
      if _storage._actualHeight != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._actualHeight, fieldNumber: 5)
      }
      if _storage._actualRefreshRateMillihz != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._actualRefreshRateMillihz, fieldNumber: 6)
      }
      if _storage._actualRotation != .rotation0 {
        try visitor.visitSingularEnumField(value: _storage._actualRotation, fieldNumber: 7)
      }
      if _storage._streamWidth != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._streamWidth, fieldNumber: 8)
      }
      if _storage._streamHeight != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._streamHeight, fieldNumber: 9)
      }
      if _storage._codec != .h264 {
        try visitor.visitSingularEnumField(value: _storage._codec, fieldNumber: 10)
      }
      if _storage._codecProfile != .profileUnspecified {
        try visitor.visitSingularEnumField(value: _storage._codecProfile, fieldNumber: 11)
      }
      if _storage._codecLevelIdc != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._codecLevelIdc, fieldNumber: 12)
      }
      if _storage._bitrateBps != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._bitrateBps, fieldNumber: 13)
      }
      if _storage._maxDatagramBytes != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._maxDatagramBytes, fieldNumber: 14)
      }
      if _storage._maxVideoPayloadBytes != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._maxVideoPayloadBytes, fieldNumber: 15)
      }
      if _storage._maxTotalChunksPerFrame != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._maxTotalChunksPerFrame, fieldNumber: 16)
      }
      if _storage._maxFrameBytes != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._maxFrameBytes, fieldNumber: 17)
      }
      if _storage._videoPort != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._videoPort, fieldNumber: 20)
      }
      if _storage._inputUdpPort != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._inputUdpPort, fieldNumber: 21)
      }
      if _storage._cursorUdpPort != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._cursorUdpPort, fieldNumber: 22)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_ModeConfirm, rhs: Resc_Control_ModeConfirm) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._sessionID != rhs_storage._sessionID {return false}
        if _storage._streamID != rhs_storage._streamID {return false}
        if _storage._configID != rhs_storage._configID {return false}
        if _storage._actualWidth != rhs_storage._actualWidth {return false}
        if _storage._actualHeight != rhs_storage._actualHeight {return false}
        if _storage._actualRefreshRateMillihz != rhs_storage._actualRefreshRateMillihz {return false}
        if _storage._actualRotation != rhs_storage._actualRotation {return false}
        if _storage._streamWidth != rhs_storage._streamWidth {return false}
        if _storage._streamHeight != rhs_storage._streamHeight {return false}
        if _storage._codec != rhs_storage._codec {return false}
        if _storage._codecProfile != rhs_storage._codecProfile {return false}
        if _storage._codecLevelIdc != rhs_storage._codecLevelIdc {return false}
        if _storage._bitrateBps != rhs_storage._bitrateBps {return false}
        if _storage._maxDatagramBytes != rhs_storage._maxDatagramBytes {return false}
        if _storage._maxVideoPayloadBytes != rhs_storage._maxVideoPayloadBytes {return false}
        if _storage._maxTotalChunksPerFrame != rhs_storage._maxTotalChunksPerFrame {return false}
        if _storage._maxFrameBytes != rhs_storage._maxFrameBytes {return false}
        if _storage._videoPort != rhs_storage._videoPort {return false}
        if _storage._inputUdpPort != rhs_storage._inputUdpPort {return false}
        if _storage._cursorUdpPort != rhs_storage._cursorUdpPort {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_ModeReject: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ModeReject"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reason\0\u{1}message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.reason) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.reason != .unspecified {
      try visitor.visitSingularEnumField(value: self.reason, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_ModeReject, rhs: Resc_Control_ModeReject) -> Bool {
    if lhs.reason != rhs.reason {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_ModeReject.Reason: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0REASON_UNSPECIFIED\0\u{1}INCOMPATIBLE_PROTOCOL_VERSION\0\u{1}NOT_PAIRED\0\u{1}UNSUPPORTED_MODE\0\u{1}INTERNAL_ERROR\0")
}

extension Resc_Control_StartStreaming: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StartStreaming"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}config_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.configID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularUInt32Field(value: self.streamID, fieldNumber: 1)
    }
    if self.configID != 0 {
      try visitor.visitSingularUInt32Field(value: self.configID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_StartStreaming, rhs: Resc_Control_StartStreaming) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.configID != rhs.configID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_StreamingReady: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamingReady"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}config_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.configID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularUInt32Field(value: self.streamID, fieldNumber: 1)
    }
    if self.configID != 0 {
      try visitor.visitSingularUInt32Field(value: self.configID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_StreamingReady, rhs: Resc_Control_StreamingReady) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.configID != rhs.configID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_Stats: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Stats"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}packet_loss_rate\0\u{3}frame_drop_rate\0\u{3}decode_ms_p95\0\u{4}\u{7}misrouted_packets\0\u{3}unsupported_version_packets\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.packetLossRate) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.frameDropRate) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.decodeMsP95) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.misroutedPackets) }()
      case 11: try { try decoder.decodeSingularUInt32Field(value: &self.unsupportedVersionPackets) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.packetLossRate.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.packetLossRate, fieldNumber: 1)
    }
    if self.frameDropRate.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.frameDropRate, fieldNumber: 2)
    }
    if self.decodeMsP95 != 0 {
      try visitor.visitSingularUInt32Field(value: self.decodeMsP95, fieldNumber: 3)
    }
    if self.misroutedPackets != 0 {
      try visitor.visitSingularUInt32Field(value: self.misroutedPackets, fieldNumber: 10)
    }
    if self.unsupportedVersionPackets != 0 {
      try visitor.visitSingularUInt32Field(value: self.unsupportedVersionPackets, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_Stats, rhs: Resc_Control_Stats) -> Bool {
    if lhs.packetLossRate != rhs.packetLossRate {return false}
    if lhs.frameDropRate != rhs.frameDropRate {return false}
    if lhs.decodeMsP95 != rhs.decodeMsP95 {return false}
    if lhs.misroutedPackets != rhs.misroutedPackets {return false}
    if lhs.unsupportedVersionPackets != rhs.unsupportedVersionPackets {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_RequestIDR: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestIDR"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}config_id\0\u{1}reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.configID) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.reason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularUInt32Field(value: self.streamID, fieldNumber: 1)
    }
    if self.configID != 0 {
      try visitor.visitSingularUInt32Field(value: self.configID, fieldNumber: 2)
    }
    if self.reason != .unspecified {
      try visitor.visitSingularEnumField(value: self.reason, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_RequestIDR, rhs: Resc_Control_RequestIDR) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.configID != rhs.configID {return false}
    if lhs.reason != rhs.reason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_RequestIDR.Reason: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0REASON_UNSPECIFIED\0\u{1}FRAME_LOSS\0\u{1}DECODE_ERROR\0\u{1}PARAMETER_SET_LOSS\0")
}

extension Resc_Control_DisplaySettings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DisplaySettings"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}warm_strength\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.warmStrength) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.warmStrength.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.warmStrength, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_DisplaySettings, rhs: Resc_Control_DisplaySettings) -> Bool {
    if lhs.warmStrength != rhs.warmStrength {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_KeyEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KeyEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}seq\0\u{3}is_down\0\u{3}hid_usage\0\u{3}logical_keysym\0\u{2}\u{6}modifiers\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.seq) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isDown) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.hidUsage) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.logicalKeysym) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.modifiers) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.seq != 0 {
      try visitor.visitSingularUInt32Field(value: self.seq, fieldNumber: 1)
    }
    if self.isDown != false {
      try visitor.visitSingularBoolField(value: self.isDown, fieldNumber: 2)
    }
    if self.hidUsage != 0 {
      try visitor.visitSingularUInt32Field(value: self.hidUsage, fieldNumber: 3)
    }
    if self.logicalKeysym != 0 {
      try visitor.visitSingularUInt32Field(value: self.logicalKeysym, fieldNumber: 4)
    }
    if self.modifiers != 0 {
      try visitor.visitSingularUInt32Field(value: self.modifiers, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_KeyEvent, rhs: Resc_Control_KeyEvent) -> Bool {
    if lhs.seq != rhs.seq {return false}
    if lhs.isDown != rhs.isDown {return false}
    if lhs.hidUsage != rhs.hidUsage {return false}
    if lhs.logicalKeysym != rhs.logicalKeysym {return false}
    if lhs.modifiers != rhs.modifiers {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_StopStreaming: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StopStreaming"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reason\0\u{1}message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.reason) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.reason != .unspecified {
      try visitor.visitSingularEnumField(value: self.reason, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Resc_Control_StopStreaming, rhs: Resc_Control_StopStreaming) -> Bool {
    if lhs.reason != rhs.reason {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Resc_Control_StopStreaming.Reason: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0REASON_UNSPECIFIED\0\u{1}USER_REQUEST\0\u{1}GRACE_PERIOD_EXPIRED\0\u{1}INTERNAL_ERROR\0")
}
