// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cursor.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Resc_Cursor_CursorShape: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case cursorArrow // = 0
  case cursorIbeam // = 1
  case cursorCrosshair // = 2
  case cursorOpenHand // = 3
  case cursorClosedHand // = 4
  case cursorPointingHand // = 5
  case cursorResizeN // = 6
  case cursorResizeS // = 7
  case cursorResizeE // = 8
  case cursorResizeW // = 9
  case cursorResizeNs // = 10
  case cursorResizeEw // = 11
  case cursorResizeNesw // = 12
  case cursorResizeNwse // = 13
  case cursorNotAllowed // = 14
  case cursorWait // = 15
  case UNRECOGNIZED(Int)

  public init() {
    self = .cursorArrow
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .cursorArrow
    case 1: self = .cursorIbeam
    case 2: self = .cursorCrosshair
    case 3: self = .cursorOpenHand
    case 4: self = .cursorClosedHand
    case 5: self = .cursorPointingHand
    case 6: self = .cursorResizeN
    case 7: self = .cursorResizeS
    case 8: self = .cursorResizeE
    case 9: self = .cursorResizeW
    case 10: self = .cursorResizeNs
    case 11: self = .cursorResizeEw
    case 12: self = .cursorResizeNesw
    case 13: self = .cursorResizeNwse
    case 14: self = .cursorNotAllowed
    case 15: self = .cursorWait
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .cursorArrow: return 0
    case .cursorIbeam: return 1
    case .cursorCrosshair: return 2
    case .cursorOpenHand: return 3
    case .cursorClosedHand: return 4
    case .cursorPointingHand: return 5
    case .cursorResizeN: return 6
    case .cursorResizeS: return 7
    case .cursorResizeE: return 8
    case .cursorResizeW: return 9
    case .cursorResizeNs: return 10
    case .cursorResizeEw: return 11
    case .cursorResizeNesw: return 12
    case .cursorResizeNwse: return 13
    case .cursorNotAllowed: return 14
    case .cursorWait: return 15
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Resc_Cursor_CursorShape] = [
    .cursorArrow,
    .cursorIbeam,
    .cursorCrosshair,
    .cursorOpenHand,
    .cursorClosedHand,
    .cursorPointingHand,
    .cursorResizeN,
    .cursorResizeS,
    .cursorResizeE,
    .cursorResizeW,
    .cursorResizeNs,
    .cursorResizeEw,
    .cursorResizeNesw,
    .cursorResizeNwse,
    .cursorNotAllowed,
    .cursorWait,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Resc_Cursor_CursorShape: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CURSOR_ARROW\0\u{1}CURSOR_IBEAM\0\u{1}CURSOR_CROSSHAIR\0\u{1}CURSOR_OPEN_HAND\0\u{1}CURSOR_CLOSED_HAND\0\u{1}CURSOR_POINTING_HAND\0\u{1}CURSOR_RESIZE_N\0\u{1}CURSOR_RESIZE_S\0\u{1}CURSOR_RESIZE_E\0\u{1}CURSOR_RESIZE_W\0\u{1}CURSOR_RESIZE_NS\0\u{1}CURSOR_RESIZE_EW\0\u{1}CURSOR_RESIZE_NESW\0\u{1}CURSOR_RESIZE_NWSE\0\u{1}CURSOR_NOT_ALLOWED\0\u{1}CURSOR_WAIT\0")
}
