// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: input.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Resc_Input_MouseButton: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case left // = 0
  case right // = 1
  case middle // = 2

  /// X1 / back button
  case back // = 3

  /// X2 / forward button
  case forward // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .left
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .left
    case 1: self = .right
    case 2: self = .middle
    case 3: self = .back
    case 4: self = .forward
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .left: return 0
    case .right: return 1
    case .middle: return 2
    case .back: return 3
    case .forward: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Resc_Input_MouseButton] = [
    .left,
    .right,
    .middle,
    .back,
    .forward,
  ]

}

public enum Resc_Input_InputEventType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case inputMouseMove // = 0
  case inputMouseDown // = 1
  case inputMouseUp // = 2
  case inputScroll // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .inputMouseMove
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .inputMouseMove
    case 1: self = .inputMouseDown
    case 2: self = .inputMouseUp
    case 3: self = .inputScroll
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .inputMouseMove: return 0
    case .inputMouseDown: return 1
    case .inputMouseUp: return 2
    case .inputScroll: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Resc_Input_InputEventType] = [
    .inputMouseMove,
    .inputMouseDown,
    .inputMouseUp,
    .inputScroll,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Resc_Input_MouseButton: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MOUSE_BUTTON_LEFT\0\u{1}MOUSE_BUTTON_RIGHT\0\u{1}MOUSE_BUTTON_MIDDLE\0\u{1}MOUSE_BUTTON_BACK\0\u{1}MOUSE_BUTTON_FORWARD\0")
}

extension Resc_Input_InputEventType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0INPUT_MOUSE_MOVE\0\u{1}INPUT_MOUSE_DOWN\0\u{1}INPUT_MOUSE_UP\0\u{1}INPUT_SCROLL\0")
}
