#!/usr/bin/env bash
set -euo pipefail

# Generate protobuf code for both Swift and Rust from proto/ definitions.
# Uses local protoc + plugins installed in tools/bin/ — no system-wide installs.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TOOLS_BIN="$SCRIPT_DIR/bin"
PROTO_DIR="$PROJECT_ROOT/proto"

# Pinned versions
PROTOC_VERSION="27.3"
SWIFT_PROTOBUF_VERSION="1.28.1"

# Output directories
SWIFT_OUT="$PROJECT_ROOT/mac-host/Sources/Protocol"
RUST_OUT="$PROJECT_ROOT/ubuntu-client/crates/protocol/src"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[proto]${NC} $*"; }
warn() { echo -e "${YELLOW}[proto]${NC} $*"; }
err() { echo -e "${RED}[proto]${NC} $*" >&2; }

# --- Ensure local protoc ---
ensure_protoc() {
    local protoc="$TOOLS_BIN/protoc"
    if [[ -x "$protoc" ]]; then
        local ver
        ver=$("$protoc" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+' | head -1)
        log "protoc found: v$ver"
        return 0
    fi

    log "Installing protoc v${PROTOC_VERSION} to $TOOLS_BIN..."
    mkdir -p "$TOOLS_BIN"

    local os arch zip_name url
    os="$(uname -s)"
    arch="$(uname -m)"

    case "$os" in
        Darwin)
            case "$arch" in
                arm64) zip_name="protoc-${PROTOC_VERSION}-osx-aarch_64.zip" ;;
                x86_64) zip_name="protoc-${PROTOC_VERSION}-osx-x86_64.zip" ;;
                *) err "Unsupported arch: $arch"; return 1 ;;
            esac
            ;;
        Linux)
            case "$arch" in
                x86_64|amd64) zip_name="protoc-${PROTOC_VERSION}-linux-x86_64.zip" ;;
                aarch64|arm64) zip_name="protoc-${PROTOC_VERSION}-linux-aarch_64.zip" ;;
                *) err "Unsupported arch: $arch"; return 1 ;;
            esac
            ;;
        *) err "Unsupported OS: $os"; return 1 ;;
    esac

    url="https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/${zip_name}"
    local tmpdir
    tmpdir=$(mktemp -d)
    trap "rm -rf '$tmpdir'" EXIT

    curl -sSL "$url" -o "$tmpdir/protoc.zip"
    unzip -qo "$tmpdir/protoc.zip" -d "$tmpdir/protoc"
    cp "$tmpdir/protoc/bin/protoc" "$TOOLS_BIN/protoc"
    chmod +x "$TOOLS_BIN/protoc"

    # Also copy well-known types
    mkdir -p "$SCRIPT_DIR/include"
    cp -r "$tmpdir/protoc/include/"* "$SCRIPT_DIR/include/" 2>/dev/null || true

    log "protoc v${PROTOC_VERSION} installed"
}

# --- Ensure Swift protoc plugin ---
ensure_swift_plugin() {
    local plugin="$TOOLS_BIN/protoc-gen-swift"
    if [[ -x "$plugin" ]]; then
        log "protoc-gen-swift found"
        return 0
    fi

    log "Building protoc-gen-swift (requires swift)..."
    if ! command -v swift &>/dev/null; then
        warn "swift not found — skipping Swift codegen"
        return 1
    fi

    local tmpdir
    tmpdir=$(mktemp -d)
    trap "rm -rf '$tmpdir'" EXIT

    git clone --depth 1 --branch "${SWIFT_PROTOBUF_VERSION}" \
        https://github.com/apple/swift-protobuf.git "$tmpdir/swift-protobuf" 2>/dev/null

    (cd "$tmpdir/swift-protobuf" && swift build -c release --product protoc-gen-swift 2>/dev/null)
    cp "$tmpdir/swift-protobuf/.build/release/protoc-gen-swift" "$TOOLS_BIN/"
    chmod +x "$TOOLS_BIN/protoc-gen-swift"
    log "protoc-gen-swift installed"
}

# --- Generate ---
generate_swift() {
    local plugin="$TOOLS_BIN/protoc-gen-swift"
    if [[ ! -x "$plugin" ]]; then
        warn "Skipping Swift codegen (no protoc-gen-swift)"
        return 0
    fi

    mkdir -p "$SWIFT_OUT"
    log "Generating Swift code → $SWIFT_OUT"

    "$TOOLS_BIN/protoc" \
        --proto_path="$PROTO_DIR" \
        --plugin="protoc-gen-swift=$plugin" \
        --swift_out="$SWIFT_OUT" \
        --swift_opt=Visibility=Public \
        "$PROTO_DIR"/*.proto

    log "Swift protobuf generated: $(ls "$SWIFT_OUT"/*.swift 2>/dev/null | wc -l | tr -d ' ') files"
}

generate_rust() {
    # Rust codegen via prost-build is done in build.rs, but we can also
    # generate standalone .rs files here for committed code.
    mkdir -p "$RUST_OUT"
    log "Rust protobuf: generated via prost-build in Cargo build.rs"
    log "  Proto files available at: $PROTO_DIR"

    # Write a helper module file that build.rs output will populate
    cat > "$RUST_OUT/mod.rs" << 'EOF'
// Auto-generated module file. Do not edit manually.
// Protobuf types are generated by prost-build in build.rs.

pub mod resc_control {
    include!(concat!(env!("OUT_DIR"), "/resc.control.rs"));
}
EOF
    log "Rust module stub written to $RUST_OUT/mod.rs"
}

# --- Main ---
main() {
    log "Proto source: $PROTO_DIR"
    log "Proto files: $(ls "$PROTO_DIR"/*.proto 2>/dev/null | xargs -n1 basename | tr '\n' ' ')"

    ensure_protoc
    ensure_swift_plugin
    generate_swift
    generate_rust

    log "Done."
}

main "$@"
